export ZSH="/home/davidlemlerm/.oh-my-zsh"
ZSH_THEME="agnoster"
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"
HIST_STAMPS="yyyy-mm-dd"
plugins=(adb archlinux bundler gem git history history-substring-search npm pip rsync safe-paste sublime sublime-merge vscode)
source $ZSH/oh-my-zsh.sh
export LANG=en_US.UTF-8
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Aliases
alias cls='clear'
alias copy='cp'
alias dir='ll'
alias disableinternet='sudo ufw default deny outgoing'
alias enableinternet='sudo ufw default allow outgoing'
alias grub-reinstall='sudo grub-install /dev/sda && sudo update-grub'
alias ifconfig='ip a'
alias ipconfig='ifconfig'
alias la='ls -a'
alias ll='ls -l'
alias lla='ls -la'
alias lockuser='sudo usermod -L'
alias move='mv'
alias pacinstall='sudo pacman -S --needed'
alias pacnew='find / -name "*.pacnew" 2> /dev/null'
alias pacsearch='pacman -Ss'
alias ssh-lss='ssh 45.33.24.185'
alias start='screen'
alias unlockuser='sudo usermod -U'
alias zshrc='nvim ~/.zshrc && source ~/.zshrc'

export PATH="$HOME/.gem/ruby/2.7.0/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"

if [[ -n $SSH_CONNECTION ]]; then
	alias sudo='sudo -A'
	export SSH_ASKPASS="ksshaskpass"
	export SUDO_ASKPASS="/usr/bin/ksshaskpass"
fi

if [[ "$-" = *i* ]]; then
	neofetch
fi
